skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pre_req_vault = "2vWNPAB91GLTe46j1Zh18BKB1SK6E4W1tWoKQ6uT4CLi"

[programs.devnet]
pre_req_vault = "2vWNPAB91GLTe46j1Zh18BKB1SK6E4W1tWoKQ6uT4CLi"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
testsvm = "cargo test"

[hooks]
